# Generated by Django 5.0.3 on 2024-05-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantpersonalfile',
            name='average_mark_exams',
            field=models.FloatField(blank=True, null=True, verbose_name='Средний балл по результатам сдачи экзаменов'),
        ),
    ]
