# Generated by Django 5.0.3 on 2024-04-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantpersonalfile',
            options={'ordering': ('last_name',), 'verbose_name': 'Личное дело', 'verbose_name_plural': 'Личные дела'},
        ),
        migrations.AlterField(
            model_name='applicantpersonalfile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество'),
        ),
    ]
