# Generated by Django 5.0.3 on 2024-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_applicantpersonalfile_average_mark_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantpersonalfile',
            name='privilege_description',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснение по льготе'),
        ),
    ]
