# Generated by Django 5.0.3 on 2024-05-31 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_applicantpersonalfile_privilege_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantpersonalfile',
            name='is_chaes',
            field=models.BooleanField(default=False, verbose_name='ЧАЭС (да/нет)'),
        ),
        migrations.AddField(
            model_name='applicantpersonalfile',
            name='is_employee_child',
            field=models.BooleanField(default=False, verbose_name='ЧАЭС (да/нет)'),
        ),
        migrations.AddField(
            model_name='applicantpersonalfile',
            name='math_mark_after_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отметка по метематике после 6 класса'),
        ),
        migrations.AddField(
            model_name='applicantpersonalfile',
            name='physical_training_mark_after_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отметка по физической культуре после 6 класса'),
        ),
        migrations.AlterField(
            model_name='addresscity',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.addressdistrict', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='addressdistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.addressregion', verbose_name='Область'),
        ),
    ]
