# Generated by Django 5.0.3 on 2024-04-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_rename_privilege_applicantpersonalfile_there_is_privilege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantpersonalfile',
            old_name='there_is_privilege',
            new_name='privilege',
        ),
    ]
