# Generated by Django 5.0.3 on 2024-04-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_rename_there_is_privilege_applicantpersonalfile_privilege'),
    ]

    operations = [
        migrations.CreateModel(
            name='VVK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vvk_result', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ВВК результат',
                'verbose_name_plural': 'ВВК результаты',
                'ordering': ('vvk_result',),
            },
        ),
        migrations.RemoveField(
            model_name='applicantpersonalfile',
            name='is_fit',
        ),
        migrations.AddField(
            model_name='applicantpersonalfile',
            name='fit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.vvk', verbose_name='Прохождение ВВК'),
        ),
    ]
