# Generated by Django 5.0.3 on 2024-05-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_applicantpersonalfile_where_studied_previously'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantpersonalfile',
            name='is_large_family',
            field=models.BooleanField(default=False, verbose_name='Многодетная семья (да/нет)'),
        ),
    ]
