# Generated by Django 5.0.3 on 2024-04-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_applicantpersonalfile_sum_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantpersonalfile',
            name='sum_mark',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма баллов по результатам вступительных испытаний'),
        ),
    ]
