# Generated by Django 5.0.3 on 2024-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_alter_applicantpersonalfile_sum_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantpersonalfile',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='applicantpersonalfile',
            name='fit_diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Диагноз (если не годен)'),
        ),
        migrations.AlterField(
            model_name='applicantpersonalfile',
            name='class_he_goes_to',
            field=models.IntegerField(choices=[(7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс')], verbose_name='В какой класс поступает'),
        ),
    ]
