# Generated by Django 5.0.3 on 2024-05-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_addresscity_district_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscity',
            name='district_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район прописью (не заполнять)'),
        ),
    ]
